Language: python
python:
  - "3.6"

services:
  - docker

before_script:
  - sudo apt-get install python3.6  
  - pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"
